# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ca6d4c49063cf0c19f2a4f374595d0b312909106b704a61b69f44eebc6dd93563cdb31bf6cab75ac0626710b3278f5e33a9f14a61e5be5a856e9a6a5e8eee1c

test:
  secret_key_base: 5592759c09b018e3bdfcb84f7a4e883c45c45e8c3a0af763da8842562d9c9eb49dfa7d6d73bb32450ecc90953ab6e8b617745a51ec374398deb90eef1ed7b35b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 6ca6d4c49063cf0c19f2a4f374595d0b312909106b704a61b69f44eebc6dd93563cdb31bf6cab75ac0626710b3278f5e33a9f14a61e5be5a856e9a6a5e8eee1c
